name: my_website
description: "This is a personal web app."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#  cupertino_icons: ^1.0.6

  # web related
  url_strategy: ^0.2.0
  url_launcher: ^6.3.0
  flutter_html: ^3.0.0-beta.2

  # design related
  flutter_svg: ^2.0.10+1
  flip_card: ^0.7.0
  responsive_framework: ^1.4.0
#  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  carousel_slider: ^5.0.0
  # state management
  provider: ^6.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/
   - assets/icons/

  fonts:
   - family: Gupter
     fonts:
       - asset: assets/fonts/Gupter-Bold.ttf
       - asset: assets/fonts/Gupter-Medium.ttf
       - asset: assets/fonts/Gupter-Regular.ttf

   - family: HarryPotter
     fonts:
       - asset: assets/fonts/HarryPotter.ttf

   - family: Poppins
     fonts:
       - asset: assets/fonts/poppins/Poppins-Regular.ttf
       - asset: assets/fonts/poppins/Poppins-Light.ttf
       - asset: assets/fonts/poppins/Poppins-Bold.ttf
         weight: 900
       - asset: assets/fonts/poppins/Poppins-Medium.ttf
         weight: 300
       - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
         weight: 500
       - asset: assets/fonts/poppins/Poppins-Italic.ttf
         style: italic

  #   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700


  
  

  
  
  
  
  

  
  
  
